# Generated by Django 5.0.3 on 2024-05-12 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='patientAppoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yourname', models.CharField(max_length=70)),
                ('youremail', models.EmailField(max_length=254)),
                ('yourmobile', models.IntegerField()),
                ('yourdoctor', models.CharField(max_length=70)),
                ('yourdate', models.DateField()),
                ('yourtime', models.TimeField()),
                ('problem', models.CharField(max_length=200)),
            ],
        ),
    ]
